services:
  app:
    build: .
    container_name: benderBar-node
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: npm run dev
# mysql:
#     image: mysql:8.0
#     container_name: benderBar-mysql
#     environment:
#       MYSQL_ROOT_PASSWORD: root
#       MYSQL_DATABASE: root
#     ports:
#       - "3306:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql